# 生产环境配置文件。当应用部署到生产环境时，这个文件中的配置将被使用。它通常包含生产环境的数据库连接、API密钥、优化性能的配置等。

server:
  port: 8091

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml